spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=myfancysecret
server.port=8083

spring.application.name=users-api
spring.zipkin.baseUrl=http://127.0.0.1:9411/
spring.sleuth.sampler.percentage=100.0