name: CI - Build Docker Images

on:
  push:

  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: auth-api
            path: ./auth-api
            tech: go
          - name: todos-api
            path: ./todos-api
            tech: node
          - name: users-api
            path: ./users-api
            tech: java
          - name: frontend
            path: ./frontend
            tech: node
          - name: log-message-processor
            path: ./log-message-processor
            tech: python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Docker build steps (for all services good)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service.path }}
          file: ${{ matrix.service.path }}/Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.service.name }}:${{ github.sha }}

  trigger-cd:
    needs: build-and-test
    uses: ./.github/workflows/cd.yml

    with:
      sha: ${{ github.sha }}
    secrets: inherit
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.base_ref == 'main' && github.event.pull_request.draft == false)
