name: infra - Terraform Container Apps

on:
  push:
    branches:
      - main
    paths:
      - "terraform/container-apps/**"
      - ".github/workflows/infra-container-apps.yml"
  pull_request:
    branches:
      - main
    paths:
      - "terraform/container-apps/**"
      - ".github/workflows/infra-container-apps.yml"

jobs:
  deploy-container-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform to deploy Container Apps
        run: bash ./terraform/scripts/deploy-container-apps.sh
        shell: bash